### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by birdflies** [novasky0709/NSEPN#1]
Hi, do you have the paper if this code?

**Comment by yuzewang1998** [comment]
Hi @birdflies ,we don't have paper yet.We are doing some experiment for editable NeRF. If we release the paper,I will reply to you here.

**Comment by birdflies** [comment]
Thanks,  editable NeRF is based on point nerf~

**Comment by birdflies** [comment]
Now, has this code conducted scene editing Point-nerf? 
would you like to update readme.md?

**Comment by yuzewang1998** [comment]
> Now, has this code conducted scene editing Point-nerf? would you like to update readme.md?

Hi,we should do more experiments to improve the result.I will update readme.md timely when we are ready.
Thanks.
